Try CI on TheUtility

diff --git a/.github/workflows/build-native.yml b/.github/workflows/build-native.yml
--- a/.github/workflows/build-native.yml
+++ b/.github/workflows/build-native.yml
@@ -1,13 +1,12 @@
 name: Build Native
 
 on:
-  # workflow_dispatch
   push:
-    # tags:
-    #   - "v*"
+    branches:
+    - master
 
 env:
-  PROJECT_NAME: TemplateProject
+  PROJECT_NAME: TheUtility
 
 jobs:
   build:
@@ -42,11 +41,22 @@ jobs:
         ./download-prebuilt-libs.sh
       shell: bash
 
+    - name: Import Certificate
+        uses: apple-actions/import-codesign-certs@v1
+        with: 
+          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
+          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
+
     - name: Build macOS
       if: matrix.os == 'macOS-latest'
+      env:
+        APPLE_ID: ${{ secrets.APPLE_ID }}
+        APP_SPECIFIC_PWD: ${{ secrets.APP_SPECIFIC_PWD }}
+        CERT_NAME_HASH: ${{ secrets.CERT_NAME_HASH }}
+        TEAM_ID: ${{ secrets.TEAM_ID }}
       run: |
         cd ${{env.PROJECT_NAME}}/scripts
-        ./makedist-mac.sh full zip
+        ./makedist-mac.sh
       shell: bash
 
     - name: Add msbuild to PATH (Windows)
@@ -57,7 +67,7 @@ jobs:
       if: matrix.os == 'windows-latest'
       run: |
         cd ${{env.PROJECT_NAME}}\scripts
-        .\makedist-win.bat full zip
+        .\makedist-win.bat
       shell: pwsh
 
     - name: Upload artifact
@@ -76,7 +86,10 @@ jobs:
         include:
           - os: macos-latest
             artifact_ext: mac
+            PluginVal: ./pluginval.app/Contents/MacOS/pluginval --strictness-level 10 --block-sizes 44100,48000,88200,96000,176400,192000 --skip-gui-tests --validate-in-process --validate
+            AuVal: auval -vt aufx TZhe # change mfg tag and plugin type accordingly
           - os: windows-latest
+            PluginVal: .\pluginval.exe --strictness-level 10 --block-sizes 44100,48000,88200,96000,176400,192000 --skip-gui-tests --validate-in-process --validate
             artifact_ext: win
 
     steps:
@@ -90,16 +103,23 @@ jobs:
           unzip *-${{matrix.artifact_ext}}.zip
         shell: bash
 
-      - name: Pluginval (macOS)
+      - name: Pluginval and auval (macOS)
         if: matrix.os == 'macos-latest'
         run: |
           curl -L "https://github.com/Tracktion/pluginval/releases/download/latest_release/pluginval_macOS.zip" -o pluginval.zip
           unzip pluginval
-          pluginval.app/Contents/MacOS/pluginval --skip-gui-tests --validate-in-process --output-dir "./bin" --validate ${{env.PROJECT_NAME}}.vst3 || exit 1
+          ${{matrix.PluginVal}} Default/${{env.PROJECT_NAME}}.vst3 || exit 1
+          ${{matrix.PluginVal}} Compatible/${{env.PROJECT_NAME}}.vst3 || exit 1
           mkdir -p ~/Library/Audio/Plug-Ins/Components
-          mv ${{env.PROJECT_NAME}}.component ~/Library/Audio/Plug-Ins/Components
+          mv Default/${{env.PROJECT_NAME}}.component ~/Library/Audio/Plug-Ins/Components
           pgrep -x AudioComponentRegistrar >/dev/null && killall -9 AudioComponentRegistrar; echo "killed AudioComponentRegistrar" || echo "AudioComponentRegistrar Process not found"
-          pluginval.app/Contents/MacOS/pluginval --skip-gui-tests --validate-in-process --output-dir "./bin" --validate ~/Library/Audio/Plug-Ins/Components/${{env.PROJECT_NAME}}.component || exit 1
+          ${{matrix.PluginVal}} ~/Library/Audio/Plug-Ins/Components/${{env.PROJECT_NAME}}.component || exit 1
+          ${{matrix.AuVal}} || exit 1
+          sudo rm -rf ~/Library/Audio/Plug-Ins/Components/${{env.PROJECT_NAME}}.component
+          mv Compatible/${{env.PROJECT_NAME}}.component ~/Library/Audio/Plug-Ins/Components
+          pgrep -x AudioComponentRegistrar >/dev/null && killall -9 AudioComponentRegistrar; echo "killed AudioComponentRegistrar" || echo "AudioComponentRegistrar Process not found"
+          ${{matrix.PluginVal}} ~/Library/Audio/Plug-Ins/Components/${{env.PROJECT_NAME}}.component || exit 1
+          ${{matrix.AuVal}} || exit 1
         shell: bash
 
       - name: Pluginval (Windows)
@@ -107,12 +127,6 @@ jobs:
         run: |
           powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest https://github.com/Tracktion/pluginval/releases/download/latest_release/pluginval_Windows.zip -OutFile pluginval.zip"
           powershell -Command "Expand-Archive pluginval.zip -DestinationPath ."
-          pluginval.exe --skip-gui-tests --validate-in-process --output-dir "./bin" --validate ${{env.PROJECT_NAME}}.vst3
+          ${{matrix.PluginVal}} ${{env.PROJECT_NAME}}.vst3
           if %ERRORLEVEL% neq 0 exit /b 1
         shell: cmd
-
-      - name: Upload artifact
-        uses: actions/upload-artifact@v1
-        with:
-          name: ${{env.PROJECT_NAME}}-${{matrix.artifact_ext}}-pluginval
-          path: ./bin/
